version: '3.8'
services:
  app:
    build: .
    command: /bin/sh -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build: .
    command: celery -A celery_config.app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data: