name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: practice_notes_db  
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Python
        uses: actions/setup-python@v5  
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug PostgreSQL
        run: |
          docker ps
          docker logs $(docker ps -q --filter "ancestor=postgres")
        continue-on-error: true  

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            if docker exec $(docker ps -q --filter "ancestor=postgres") pg_isready -U postgres; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Install redis-tools
        run: sudo apt-get update && sudo apt-get install -y redis-tools
      - name: Wait for Redis
        run: |
          for i in {1..30}; do
            if docker exec $(docker ps -q --filter "ancestor=redis") redis-cli ping | grep -q PONG; then
              echo "Redis is ready!"
              break
            fi
            echo "Waiting for Redis..."
            sleep 2
          done

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: pytest tests

      - name: Build Docker image
        run: docker build -t my-notes-app:latest -f dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-notes-app:latest ${{ secrets.DOCKER_USERNAME }}/my-notes-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-notes-app:latest

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull and push Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-notes-app:latest
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-notes-app:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}